version: '2'
services:
    seed:
        build: .
        ports:
          - '2551:2551'
          - '8080:8080'
        command: seed 0.0.0.0 2551 akka.tcp://ClusterSystem@seed:2551
    client1:
        build: .
        ports:
          - '2552:2552'
          - '8081:8080'
        command: client1 0.0.0.0 2552 akka.tcp://ClusterSystem@seed:2551
    client2:
        build: .
        ports:
          - '2553:2553'
          - '8082:8080'
        command: client2 0.0.0.0 2553 akka.tcp://ClusterSystem@seed:2551
