apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: crdt-seed-deployment
  spec:  
    replicas: 1
    template:
      metadata:
        labels:
          app: crdt-seed
      spec: 
        containers:
        - name: crdt-seed-pod
          image: "rwhaling/akka-crdt"
          ports:
          - containerPort: 2551
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args: ["crdt-seed", "0.0.0.0", "30002", "akka.tcp://ClusterSystem@crdt-seed:30002"]
- apiVersion: v1
  kind: Service
  metadata:
    name: crdt-seed
  spec:
    type: NodePort
    selector: 
      app: crdt-seed
    ports:
      - protocol: TCP
        port: 8080
        nodePort: 30001
        name: http
      - protocol: TCP
        port: 30002
        nodePort: 30002
        name: akka
