apiVersion: v1
kind: List
items:
# - apiVersion: v1
#   kind: PersistentVolume
#   metadata:
#     name: data-statefulset-crdt-statefulset-0
#     annotations:
#       volume.beta.kubernetes.io/storage-class: "slow"
#   spec:
#     capacity:
#       storage: 50Mi
#     accessModes:
#       - ReadWriteOnce
#     persistentVolumeReclaimPolicy: Recycle
#     hostPath:
#       path: /home/docker/data/d0
# - apiVersion: v1
#   kind: PersistentVolume
#   metadata:
#     name: data-statefulset-crdt-statefulset-1
#     annotations:
#       volume.beta.kubernetes.io/storage-class: "slow"
#   spec:
#     capacity:
#       storage: 50Mi
#     accessModes:
#       - ReadWriteOnce
#     persistentVolumeReclaimPolicy: Recycle
#     hostPath:
#       path: /home/docker/data/d1
# - apiVersion: v1
#   kind: PersistentVolume
#   metadata:
#     name: data-statefulset-crdt-statefulset-2
#     annotations:
#       volume.beta.kubernetes.io/storage-class: "slow"
#   spec:
#     capacity:
#       storage: 50Mi
#     accessModes:
#       - ReadWriteOnce
#     persistentVolumeReclaimPolicy: Recycle
#     hostPath:
#       path: /home/docker/data/d2
- apiVersion: v1
  kind: Service
  metadata:
    name: statefulset-crdt-service
  spec:
    selector:
      app: statefulset-crdt
    clusterIP: None
    ports:
      - protocol: TCP
        port: 8080
        name: http
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: statefulset-crdt-statefulset
  spec:
    serviceName: statefulset-crdt-service
    replicas: 3
    template:
      metadata:
        labels:
          app: statefulset-crdt
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: statefulset-crdt
          image: "rwhaling/akka-crdt"
          ports:
          - containerPort: 2551
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args: ["$(MY_POD_NAME)", "0.0.0.0", "2551", "akka.tcp://ClusterSystem@statefulset-crdt-statefulset-0.statefulset-crdt-service:2551"]
          volumeMounts:
          - name: data
            mountPath: /data
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 30Mi
