apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: three-pod-crdt-deployment
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: three-pod-crdt
      spec: 
        containers:
        - name: three-pod-crdt
          image: "rwhaling/akka-crdt"
          ports:
          - containerPort: 2551
          - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args: ["$(MY_POD_IP)", "0.0.0.0", "2551", "akka.tcp://ClusterSystem@$(MY_POD_IP):2551"]
- apiVersion: v1
  kind: Service
  metadata:
    name: three-pod-crdt-service
  spec:
    type: NodePort
    selector:
      app: three-pod-crdt
    ports:
      - protocol: TCP
        port: 8080
        nodePort: 30002
        name: http